---
apiVersion: v1
kind: AccessControlEntry
metadata:
  name: acl-topic-a-b
  namespace: myNamespace
spec:
  resourceType: TOPIC
  resource: abc.myTopic
  resourcePatternType: LITERAL
  permission: READ
  grantedTo: anotherNamespace